apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    service: nginx-rp
  name: nginx-rp
spec:
  replicas: 2
  template:
    metadata:
      labels:
        service: nginx-rp
    spec:
      containers:
      - image: linden416/udagram-nginx-rp:v1
        name: nginx-rp
        imagePullPolicy: Always          
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m"       
        ports:
        - containerPort: 8080
      restartPolicy: Always
