apiVersion: v1
kind: Service
metadata:
  labels:
    service: nginx-rp
  name: nginx-rp
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    service: nginx-rp
#  type: LoadBalancer    